language: generic
sudo: required
services:
 - docker
before_install:
 - docker build -t dopedead200/docker-react -f Dockerfile.dev .
script:
 - docker run -e CI=true dopehead200/docker-react npm run test
