language: generic
sudo: required
services:
 - docker
before_install:
 - docker build -t DopeHead200/docker-react -f Dockerfile.dev .
script:
 - docker run -e CI=true DopeHead200/docker-react npm run test
